"""Co-fire census (register 45; pre-registered prereg_cofire_census BEFORE
computation). OBSERVATIONAL. QUESTION, STATED: does cross-family agreement
buy precision worth its coverage cost?

Ordered cross-family pairs (base, confirming); the operator-set family
partition lives in signal_watch.COFIRE_FAMILIES (one-home rule).
Within-family pairs excluded (near-mechanical co-firing); the shared-fire
derived pair excluded outright. Split the base row's fires by presence of a
SAME-DIRECTION confirming fire within [t - w, t], w in {5, 15} minutes.
Precision definitions identical to the scoreboard's (fire bar qualifies in
the predicted direction, per-context chance). Joint cells with fires < 20
carry the registered small-n dimming; single-digit joint-n = UNMEASURABLE,
reported but never read. Coverage arithmetic: the with-stack is bounded by
the rarer leg — printed per pair.

Any pair showing real lift becomes a REGISTERED COMPOSITE (H13+) through
the front door before any signal row exists for it.
"""

import argparse
import json
import os
import subprocess
import sys

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from engine.signal_watch import COFIRE_FAMILIES as FAMILIES
from engine.signal_watch import SignalWatch
from engine.store_loader import is_sealed, lockbox_boundary, zones
from backtest.scoreboard import (PROVISIONAL_INSTRS, PROVISIONAL_STAMP,
                                 _replay, build_moves, event_derived_fires,
                                 make_cfg)

OUT = os.path.join(ROOT, "reports", "scoreboard")

WINDOWS_MIN = (5, 15)          # operator-set (activation order 2026-08-20)


def pairs():
    out = []
    for fa, rows_a in FAMILIES.items():
        for fb, rows_b in FAMILIES.items():
            if fa == fb:
                continue
            for base in rows_a:
                for conf in rows_b:
                    out.append((base, conf))
    return out


def run_instrument(instr):
    cfg = make_cfg({"session_model.extended_hours": True,
                    "session_model.ladder": True})
    watch = SignalWatch()
    engine, bars, _ = _replay(cfg, instr, engine_hook=watch.attach)
    qual, _episodes, series, _drift = build_moves(
        bars[cfg.mtf.execution_tf], bars[cfg.mtf.signal_tf],
        cfg.context.atr_period)
    ts, _cl, _segs = series
    fires = watch.fires + event_derived_fires(engine.narrative.events, cfg, bars)
    fires = [f for f in fires if not is_sealed(f["ts"])]
    boundary, gl = lockbox_boundary(), zones()["go_live"]
    by_name = {}
    for f in fires:
        by_name.setdefault(f["name"], []).append(f)

    def precision(fs):
        hits = tot = 0
        for f in fs:
            i = np.searchsorted(ts, f["ts"].value, side="right") - 1
            if i < 0:
                continue
            tot += 1
            hits += bool(qual[f["dir"]][i])
        return hits, tot

    out = {"instrument": instr,
           "status": ("provisional" if instr in PROVISIONAL_INSTRS
                      else "canonical"),
           "pairs": {}}
    for base, conf in pairs():
        bf = by_name.get(base, [])
        cf = sorted((f["ts"].value, f["dir"])
                    for f in by_name.get(conf, []))
        cts = np.array([e[0] for e in cf])
        cdirs = np.array([e[1] for e in cf])
        for w in WINDOWS_MIN:
            wns = w * 60_000_000_000
            for wname, sel in (
                    ("backtest", lambda f: f["ts"] < boundary),
                    ("forward", lambda f: f["ts"] >= gl)):
                sub = [f for f in bf if sel(f)]
                if not sub:
                    continue
                with_, without = [], []
                for f in sub:
                    lo = f["ts"].value - wns
                    i0 = np.searchsorted(cts, lo, side="left")
                    i1 = np.searchsorted(cts, f["ts"].value, side="right")
                    ok = np.any(cdirs[i0:i1] == f["dir"])
                    (with_ if ok else without).append(f)
                hw, tw = precision(with_)
                ho, to = precision(without)
                key = f"{base}->{conf}"
                out["pairs"].setdefault(key, {}).setdefault(
                    f"w{w}", {})[wname] = {
                    "with": {"n": tw, "hits": hw,
                             "pct": round(100 * hw / tw, 1) if tw else None,
                             "unmeasurable": tw < 10},
                    "without": {"n": to, "hits": ho,
                                "pct": round(100 * ho / to, 1)
                                if to else None},
                    "coverage_note": f"with-stack bounded by rarer leg "
                                     f"({conf}: {len(cf)} fires total)"}
    return out


def _emit(results, head):
    L = ["# Co-Fire Census (GENERATED by backtest.cofire)", "",
         f"Engine `{head[:9]}` — OBSERVATIONAL, pre-registered "
         "(prereg_cofire_census). QUESTION: does cross-family agreement "
         "buy precision worth its coverage cost? Confirming fire = "
         "same-direction, within [t-w, t]. Joint n<20 dimmed (°); n<10 "
         "UNMEASURABLE (reported, never read). Any pair with real lift "
         "becomes a registered composite (H13+) BEFORE any row exists.",
         ""]
    for res in results:
        inst = res["instrument"]
        L += [f"## {inst} ({res['status'].upper()})"]
        if res["status"] == "provisional":
            L += [f"> {PROVISIONAL_STAMP}"]
        L += ["", "| pair | w | window | with: pct (hits/n) "
              "| without: pct (hits/n) | Δpp |",
              "|---|---|---|---|---|---|"]
        for key, per_w in sorted(res["pairs"].items()):
            for wk, per_win in per_w.items():
                for wname, v in per_win.items():
                    wi, wo = v["with"], v["without"]
                    if wi["pct"] is None or wo["pct"] is None:
                        continue
                    d = round(wi["pct"] - wo["pct"], 1)
                    cell = f"{wi['pct']}% ({wi['hits']}/{wi['n']})"
                    if wi["unmeasurable"]:
                        cell = f"UNMEASURABLE {cell}"
                    elif wi["n"] < 20:
                        cell = f"(°{cell})"
                    L.append(f"| {key} | {wk} | {wname} "
                             f"| {cell} "
                             f"| {wo['pct']}% ({wo['hits']}/{wo['n']}) "
                             f"| {d:+.1f} |")
        L.append("")
    L += ["---", "", "Coverage notes per pair in cofire.json (same run)."]
    with open(os.path.join(OUT, "cofire.md"), "w") as f:
        f.write("\n".join(L))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--instr", nargs="*",
                    default=["uk100fut", "ger40fut", "nas100fut", "us30fut"])
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                          capture_output=True, text=True).stdout.strip()
    results = []
    for instr in a.instr:
        print(f"# cofire: {instr} ...", file=sys.stderr)
        results.append(run_instrument(instr))
    art = {"STAMP": ("OBSERVATIONAL co-fire census — pre-registered; "
                     "never validation"),
           "engine_commit": head, "results": results}
    with open(os.path.join(OUT, "cofire.json"), "w") as f:
        json.dump(art, f, indent=2, default=str)
    _emit(results, head)
    print(f"OBSERVATIONAL co-fire census -> {OUT}/cofire.md")


if __name__ == "__main__":
    main()
