"""Results front page — reports/DASHBOARD.md (register 58). Regenerated by
every Part C run. OPERATOR-FIRST, one page.

RULE: the dashboard contains NO number that is not in a stamped artifact —
it is a table of contents with headlines, never a source. Every figure
cites the artifact it was lifted from.
"""

import json
import os
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SB = os.path.join(ROOT, "reports", "scoreboard")


def _load(name, base=SB):
    try:
        return json.load(open(os.path.join(base, name)))
    except Exception:
        return None


def generate():
    from backtest.scoreboard import (register_status, register_labels,
                                     parse_questions)
    from engine.signal_watch import (FIRING_CONDITIONS, EVENT_DERIVED_ROWS,
                                     DERIVED_FIRES)
    sb = _load("hypothesis_performance.json")
    reg = register_status()
    labels = register_labels()
    qs = parse_questions()
    L = ["# DASHBOARD — results front page", "",
         "Regenerated by every Part C run. **No number here is a source — "
         "every figure lives in a stamped artifact; this page only points "
         "and headlines.**", ""]

    # (a) headline state
    n_sig = len(FIRING_CONDITIONS) + len(EVENT_DERIVED_ROWS) \
        + len(DERIVED_FIRES)
    n_q = sum(len(v) for v in qs.values())
    span = "—"
    eng = "—"
    if sb:
        eng = sb.get("engine_commit", "—")[:9]
        home = sb.get("instruments", {}).get("uk100fut", {})
        sp = home.get("store_span_1min")
        if sp:
            span = f"{sp[0][:10]} → {sp[1][:10]}"
    L += ["## State", "",
          f"- **{len(reg)} hypotheses · {n_sig} signal configurations · "
          f"{n_q} questions** (docs/hypothesis_register.md)",
          f"- Home 1M data span: {span} · scoreboard engine `{eng}` · "
          f"page generated {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}",
          ""]

    # (b) the board — one line per hypothesis (home instrument, canonical)
    L += ["## The board (home instrument; away instruments PROVISIONAL — "
          "see the scoreboard)", "",
          "| H | best current cell (initiation, conditioned where "
          "declared) | fwd trend | status |", "|---|---|---|---|"]
    if sb:
        home = sb.get("instruments", {}).get("uk100fut", {})
        sigs = home.get("signals", {})
        import re
        for n in sorted(reg):
            best = None
            trend = "→"
            for w in ("backtest", "forward"):
                blk = sigs.get(w, {})
                mv = blk.get("_moves", {})
                for key, r in blk.items():
                    if key.startswith("_") or not isinstance(r, dict):
                        continue
                    m = re.fullmatch(rf"S(\d+)-H{n}( \(either-dir\))?", key)
                    if not m or not r.get("n_fires"):
                        continue
                    ini = r.get("initiation")
                    if not ini or ini.get("pct") is None:
                        continue
                    ch = (r.get("conditioned_chance_init_pct")
                          or (mv.get("initiation_base_either_pct")
                              if r["grading"] == "either-direction"
                              else mv.get(
                                  "initiation_base_per_direction_pct")))
                    if ch is None or ini["of"] < 20:
                        continue
                    lift = round(ini["pct"] - ch, 1)
                    if best is None or abs(lift) > abs(best[0]):
                        best = (lift, key, w, ini["of"])
            # trend arrow: forward vs backtest initiation lift of the
            # hypothesis's S0 row
            def _lift(w, key):
                blk = sigs.get(w, {})
                r = blk.get(key)
                mv = blk.get("_moves", {})
                if not r or not r.get("n_fires"):
                    return None
                ini = r.get("initiation")
                if not ini or ini.get("pct") is None:
                    return None
                ch = (r.get("conditioned_chance_init_pct")
                      or (mv.get("initiation_base_either_pct")
                          if r["grading"] == "either-direction"
                          else mv.get("initiation_base_per_direction_pct")))
                return None if ch is None else ini["pct"] - ch
            s0 = f"S0-H{n}"
            lb, lf = _lift("backtest", s0), _lift("forward", s0)
            if lb is not None and lf is not None:
                trend = "↑" if lf > lb + 2 else "↓" if lf < lb - 2 else "→"
            cell = (f"{best[1]} {best[2]} {best[0]:+.1f}pp (n={best[3]})"
                    if best else "no measurable cell (n<20 everywhere)")
            L.append(f"| H{n} | {cell} | {trend} "
                     f"| {labels.get(n, '-')} |")
    L.append("")

    # (c) open questions with clocks
    L += ["## Open questions (clocks = accrued vs required; grading "
          "conditions authoritative in the register entries)", ""]

    def _sess_fires(inst, key, sess):
        if not sb:
            return None
        blk = (sb.get("instruments", {}).get(inst, {})
               .get("signals_by_session", {}).get("forward", {})
               .get(sess, {}))
        r = blk.get(key)
        return r.get("n_fires") if r else 0
    q_lines = [
        ("Q1-H1", "≥30 post-validation fwd episodes/instrument — "
         "BLOCKED: awaiting the nas100 validation evening (clock at 0)"),
        (f"Q1-H{7}", "same gate as Q1-H1 — BLOCKED on validation"),
        ("Q1-H11", f"≥30 fwd Overlap fires (home accrued: "
         f"{_sess_fires('uk100fut', 'S0-H11', 'overlap')})"),
        (f"Q2-H{9}", "≥30 fwd NY-session fires POST-VALIDATION on nas100 — "
         "clock starts at its evening"),
        (f"Q1-H{6}", f"≥30 fwd London fires (home accrued: "
         f"{_sess_fires('uk100fut', 'S0-H' + str(6), 'london')})"),
    ]
    for q, clock in q_lines:
        L.append(f"- **{q}** — {clock}")
    L.append("")

    # (d) recommendations awaiting decisions
    L += ["## Awaiting operator decisions", "",
          "- Review labels (recommendations, unactioned): H2 "
          "promote-candidate (initiation-vs-participation divergence is "
          "new input, register 53), H10 deprioritize; "
          f"S0-H{9} retirement flag (register 49).",
          "- Ratifications: promote/deprioritize criteria numbers · ±2pp "
          "marker band · session scoping · v0 recipe values (excursion "
          "geometry is the evidence base) · coil-proxy parameters.",
          "- Reads: R2 experiment verdict (r2_experiment.md — refinement "
          "costs both sides at signal granularity) · matrix survivors.",
          f"- Evenings: nas100 validation (gates Q1-H1/Q1-H{7}/Q2-H{9}) → "
          "ger40 → us30; thin-tape probe (standalone, ~50 min).",
          ""]

    # (e) the map
    L += ["## Map — what answers what (reports/scoreboard/ unless noted)",
          "",
          "- `hypothesis_performance.md|.json` — how every signal grades "
          "(dual-convention). Read weekly.",
          "- `READING_GUIDE.md` — how to read the board. Read once, "
          "reread after convention changes.",
          "- `recipe_performance.md|.json` — what fires would have paid "
          "under explicit exits. Read weekly; values discussion input.",
          "- `excursion_geometry.md|.json` — stop-width + target-reach "
          "curves. Read at the v1 recipe-values discussion.",
          "- `conditioning_matrix.md|.json` — where signals work/fail by "
          f"state; grades Q1-H11/Q2-H{9}/Q1-H{6}. Read weekly.",
          "- `cofire.md|.json` — does cross-family agreement help "
          "(composites gate). Read weekly, expect UNMEASURABLE.",
          "- `vwap_census.md|.json` / `drift_census.md|.json` — VWAP and "
          "drift verdicts (nothing survives / no base-rate change). Read "
          "on change only.",
          "- `location_census.md|.json` — exhaustion-family × volume map "
          "(starved; accruing). Read monthly.",
          "- `flip_cut.md|.json` — ARCHIVED standing reference (why "
          "narrative exits are stage-scoped).",
          "- `r2_experiment.md|.json` — the refinement question's "
          "evidence. Read once, at the R2 ruling.",
          "- `reports/forward/` — migration dossier. Read weekly.",
          "- `reports/backtest_v1.md` — the evidential pipeline + Part C "
          "index. The weekly 5-minute read.",
          "- `docs/backlog_status.md` — is everything moving. Glance "
          "weekly.", ""]
    return "\n".join(L)


def main():
    doc = generate()
    with open(os.path.join(ROOT, "reports", "DASHBOARD.md"), "w") as f:
        f.write(doc)
    print("dashboard -> reports/DASHBOARD.md")


if __name__ == "__main__":
    main()
