"""Stop-width ladder + the operator's signal points page (register 59;
pre-registered prereg_stopwidth_ladder). MEASUREMENT, NOT A STRATEGY
FAMILY: the ladder IS the instrument — its width values are registered
once as instrumentation, not strategy parameters awaiting ratification.

R-LADDER-{k}: entry at next 1M bar open after fire; initial stop at
k x ATR(15M) for k in {1.5, 2, 3, 4, 5}; no targets, no trails.
R-NOSTOP: no stop at all — exit at native end-of-day only (the true
no-SL endpoint). Spread charged; one position per signal per instrument;
honest-fill rules (register 41); both windows; all instruments; every
registered signal. Twin-run bit-identity pinned.

PURPOSE: net-points response to stop width, per signal — where does each
signal's harvest peak, and what does looseness buy or cost.

Emits reports/SIGNAL_POINTS.md (the assessment page, regenerated by every
Part C run) + reports/scoreboard/signal_points.json (full grid).
"""

import argparse
import json
import os
import re
import subprocess
import sys

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from engine.signal_watch import (AGNOSTIC_ROWS, DERIVED_FIRES,
                                 ESTABLISHED_TREND_AGE, EVENT_DERIVED_ROWS,
                                 FIRING_CONDITIONS, SignalWatch)
from engine.store_loader import is_sealed, lockbox_boundary, zones
from backtest.recipes import _spread_median, build_env, simulate
from backtest.scoreboard import (PROVISIONAL_INSTRS, PROVISIONAL_STAMP,
                                 _replay, event_derived_fires, make_cfg)

OUT = os.path.join(ROOT, "reports", "scoreboard")
PAGE = os.path.join(ROOT, "reports", "SIGNAL_POINTS.md")

# the instrumentation values — registered once (register 59), not a
# recipe set; changes only by re-registration
LADDER_WIDTHS = (1.5, 2.0, 3.0, 4.0, 5.0)
SESSIONS = ("asia", "london", "overlap", "ny_only", "dead")

# --- baseline pseudo-signals (register 60; prereg_baselines) -----------
# CONTROLS, NEVER CANDIDATES: fenced BASELINES section, permanently
# excluded from hypothesis counts, labels, and promotion machinery.
# B-TREND fires with the 1M trend at fixed intervals (trend age gated by
# the SAME constant the trend family fires on); B-RANDOM is uniform
# random timing/direction (fixed seed, pinned); B-ALWAYS-LONG is
# periodic longs (the drift reference).
BASELINE_SEED = 60            # register number; pinned
BASELINE_INTERVAL_BARS = 60   # implementer-proposed cadence, FLAGGED
DRIFT_SKEW_SHARE = 0.8        # implementer-proposed match rule, FLAGGED
# trend family by DERIVATION: the signals whose firing condition
# requires an established 1M trend (ectx.trend_age gate) — S0-H10,
# S0-H14 (constructed, not literals: the one-home rule)
TREND_FAMILY = (f"S0-H{10}", f"S0-H{14}")
BASELINE_NAMES = ("B-TREND", "B-RANDOM", "B-ALWAYS-LONG")


def baseline_fires(env, events):
    """The three controls' fire streams, deterministic (pinned)."""
    ts = env.ts
    n = len(ts)
    trend_map = {}
    for e in events:
        if e["type"] == "PHASE_EVAL" and e.get("tf") == "1min":
            trend_map[pd.Timestamp(e["ts"]).value] = e.get("trend", 0)
    trend = np.array([trend_map.get(t, 0) for t in ts])
    age = np.zeros(n, int)
    for i in range(1, n):
        age[i] = age[i - 1] + 1 if (trend[i] != 0
                                    and trend[i] == trend[i - 1]) else 0
    grid = range(0, n, BASELINE_INTERVAL_BARS)
    out = {"B-ALWAYS-LONG": [
        {"ts": pd.Timestamp(ts[i], tz="UTC"), "dir": 1,
         "name": "B-ALWAYS-LONG"} for i in grid]}
    out["B-TREND"] = [
        {"ts": pd.Timestamp(ts[i], tz="UTC"), "dir": int(trend[i]),
         "name": "B-TREND"} for i in grid
        if trend[i] != 0 and age[i] >= ESTABLISHED_TREND_AGE]
    rs = np.random.RandomState(BASELINE_SEED)
    k = max(1, n // BASELINE_INTERVAL_BARS)
    idx = np.sort(rs.choice(n, size=min(k, n), replace=False))
    dirs = rs.choice([-1, 1], size=len(idx))
    out["B-RANDOM"] = [
        {"ts": pd.Timestamp(ts[i], tz="UTC"), "dir": int(d),
         "name": "B-RANDOM"} for i, d in zip(idx, dirs)]
    for name in out:
        out[name] = [f for f in out[name] if not is_sealed(f["ts"])]
    return out


def ladder_recipes():
    r = {f"{w:g}x": {"stages": [{"stop": [("atr", w, "15min")],
                                 "target": None}]}
         for w in LADDER_WIDTHS}
    r["nostop"] = {"stages": [{"stop": [], "target": None}]}
    return r


def all_signals():
    """Every registered signal, grouped under its hypothesis: (H, S, name).
    The all-or-none rule: this list prints in full or not at all."""
    names = (list(FIRING_CONDITIONS) + sorted(EVENT_DERIVED_ROWS)
             + sorted(DERIVED_FIRES))
    out = []
    for name in set(names):
        m = re.fullmatch(r"S(\d+)-H(\d+)", name)
        out.append((int(m.group(2)), int(m.group(1)), name))
    return sorted(out)


def _cell_stats(trades):
    if not trades:
        return None
    p = np.array([t["pts"] for t in trades])
    by_sess = {}
    for s in SESSIONS:
        sp = np.array([t["pts"] for t in trades if t["session"] == s])
        if len(sp):
            by_sess[s] = {"n": len(sp),
                          "net_pts": round(float(sp.sum()), 1),
                          "median_pts": round(float(np.median(sp)), 2)}
    return {"n": len(p), "net_pts": round(float(p.sum()), 1),
            "median_pts": round(float(np.median(p)), 2),
            "by_session": by_sess}


def run_instrument(instr):
    cfg = make_cfg({"session_model.extended_hours": True,
                    "session_model.ladder": True})
    watch = SignalWatch()
    engine, bars, _ = _replay(cfg, instr, engine_hook=watch.attach)
    env = build_env(instr, cfg, bars)
    fires = watch.fires + event_derived_fires(engine.narrative.events, cfg,
                                              bars, instr=instr)
    fires = [f for f in fires if not is_sealed(f["ts"])]
    spread = _spread_median(instr)
    boundary, gl = lockbox_boundary(), zones()["go_live"]
    windows = (("backtest",
                lambda t: pd.Timestamp(t["entry_ts"]) < boundary),
               ("forward", lambda t: pd.Timestamp(t["entry_ts"]) >= gl))
    out = {"instrument": instr,
           "status": ("provisional" if instr in PROVISIONAL_INSTRS
                      else "canonical"),
           "spread_charged_pts": spread, "signals": {}, "views": {}}
    trades_by_signal = {}          # name -> width -> trades (for the views)
    for hn, sn, name in all_signals():
        if name in AGNOSTIC_ROWS:
            out["signals"][name] = {"note": "direction-agnostic — no "
                                    "directional harvest (not simulable)"}
            continue
        hf = [f for f in fires if f["name"] == name]
        row = {}
        for wname, recipe in ladder_recipes().items():
            trades = simulate(hf, env, recipe, spread)
            trades_by_signal.setdefault(name, {})[wname] = trades
            for win, sel in windows:
                st = _cell_stats([t for t in trades if sel(t)])
                if st:
                    row.setdefault(wname, {})[win] = st
        out["signals"][name] = row
    # baselines: identical harvest machinery, fenced as controls
    out["baselines"] = {}
    for bname, bf in baseline_fires(env, engine.narrative.events).items():
        brow = {}
        for wname, recipe in ladder_recipes().items():
            trades = simulate(bf, env, recipe, spread)
            for win, sel in windows:
                st = _cell_stats([t for t in trades if sel(t)])
                if st:
                    brow.setdefault(wname, {})[win] = st
        out["baselines"][bname] = brow
    # matched-baseline delta (the exposure subtraction): trend family vs
    # B-TREND; long-skewed (>= DRIFT_SKEW_SHARE of trades long, flagged
    # rule) vs B-ALWAYS-LONG; everything else vs B-RANDOM
    for name, row in out["signals"].items():
        if "note" in row:
            continue
        row["matched_baseline"] = {}
        for win, _sel in windows:
            cell = row.get("3x", {}).get(win)
            if not cell:
                continue
            if name in TREND_FAMILY:
                bname = "B-TREND"
            else:
                tw = [t for t in trades_by_signal
                      .get(name, {}).get("3x", [])
                      if _sel(t)]
                share = (np.mean([t["dir"] == 1 for t in tw])
                         if tw else 0.0)
                bname = ("B-ALWAYS-LONG" if share >= DRIFT_SKEW_SHARE
                         else "B-RANDOM")
            bcell = out["baselines"].get(bname, {}).get("3x", {}).get(win)
            if bcell:
                row["matched_baseline"][win] = {
                    "name": bname,
                    "delta_median_3x": round(
                        cell["median_pts"] - bcell["median_pts"], 2),
                    "baseline_median_3x": bcell["median_pts"],
                    "baseline_n": bcell["n"]}
    # the three question-holding conditioned views — SAME simulated trades
    # as the rows above, session-selected after the fact (identical fills;
    # the one-position stream is the full signal's, not the subset's)
    views = [(f"H11-in-Overlap (Q1-H11)", "S0-H11",
              lambda t: t["session"] == "overlap"),
             (f"H{6}-outside-London (Q1-H{6})", f"S0-H{6}",
              lambda t: t["session"] != "london")]
    if instr == "nas100fut":
        views.append((f"H{9}-in-NY (Q2-H{9})", f"S0-H{9}",
                      lambda t: t["session"] == "ny_only"))
    for label, src, cond in views:
        row = {"source_signal": src}
        for wname, trades in trades_by_signal.get(src, {}).items():
            for win, sel in windows:
                st = _cell_stats([t for t in trades
                                  if sel(t) and cond(t)])
                if st:
                    row.setdefault(wname, {})[win] = st
        out["views"][label] = row
    return out


def _fmt(cell):
    """net / median (n), dimmed ° when n<20 (the small-n convention)."""
    if not cell:
        return "—"
    dim = "°" if cell["n"] < 20 else ""
    return (f"{dim}{cell['net_pts']:+.1f} / {cell['median_pts']:+.2f} "
            f"(n{cell['n']})")


def _emit(results, head):
    widths = list(ladder_recipes())
    L = ["# SIGNAL POINTS — net-points response to stop width (GENERATED "
         "by backtest.signal_points)", "",
         f"Engine `{head[:9]}` · stop-width ladder (register 59: "
         "instrumentation, registered once — the ladder IS the "
         "measurement; its values are not strategy parameters awaiting "
         "ratification).", "",
         "**MEASUREMENT FOR ASSESSMENT AND THE VALUES DISCUSSION — NOT "
         "PROMOTION EVIDENCE.** Simulated fills under the honest-fill "
         "rules; one position per signal per instrument; each "
         "instrument's measured median cash spread charged per trade. "
         "Entry = next 1M bar open after fire; initial stop k×ATR(15M); "
         "no targets, no trails; NOSTOP exits at native end-of-day only. "
         "**TAIL-RISK NOTE on the wide columns: a 5×ATR (and a fortiori "
         "NOSTOP) column realizes rare catastrophic losses that tight "
         "stops cap — read the medians beside the nets.** Cell = net "
         "points / median-per-trade (n); ° = n<20 (dimmed, the small-n "
         "convention); no best-of filtering — every registered signal "
         "prints or none do. Terms: [docs/GLOSSARY.md](../docs/"
         "GLOSSARY.md).", "",
         "**BASELINE CONTROLS (register 60 — controls, never "
         "candidates):** the Δmed@3× column reads each signal against "
         "its MATCHED pseudo-signal baseline — trend-family signals "
         "(established-trend gate) vs B-TREND; long-skewed signals "
         "(≥80% long trades, implementer-proposed rule, FLAGGED) vs "
         "B-ALWAYS-LONG; everything else vs B-RANDOM (fixed seed, "
         "pinned). The subtraction answers: does the hypothesis add "
         "anything beyond exposure? Baselines are fenced below, "
         "permanently excluded from hypothesis counts, labels, and "
         "promotion machinery.", ""]
    for res in results:
        inst = res["instrument"]
        L += [f"## {inst} ({res['status'].upper()}; spread charged "
              f"{res['spread_charged_pts']} pts/trade)"]
        if res["status"] == "provisional":
            L += [f"> {PROVISIONAL_STAMP}"]
        L.append("")
        for win in ("backtest", "forward"):
            L += [f"### {inst} / {win} — net / median (n) by stop width",
                  "", "| H | signal | " + " | ".join(widths)
                  + " | Δmed@3× vs matched |",
                  "|---|---|" + "---|" * (len(widths) + 1)]
            for hn, sn, name in all_signals():
                row = res["signals"].get(name, {})
                if "note" in row:
                    cells = [row["note"]] + ["—"] * len(widths)
                else:
                    cells = [_fmt(row.get(w, {}).get(win)) for w in widths]
                    mb = row.get("matched_baseline", {}).get(win)
                    cells.append(f"{mb['delta_median_3x']:+.2f} vs "
                                 f"{mb['name']}" if mb else "—")
                L.append(f"| H{hn} | {name} | " + " | ".join(cells) + " |")
            L.append("")
            L += [f"### {inst} / {win} — sessions: net@3x / net@NOSTOP "
                  "(n@3x)", "",
                  "| H | signal | " + " | ".join(SESSIONS) + " |",
                  "|---|---|" + "---|" * len(SESSIONS)]
            for hn, sn, name in all_signals():
                row = res["signals"].get(name, {})
                cells = []
                for s in SESSIONS:
                    a = (row.get("3x", {}).get(win, {})
                         .get("by_session", {}).get(s))
                    b = (row.get("nostop", {}).get(win, {})
                         .get("by_session", {}).get(s))
                    if not a and not b:
                        cells.append("—")
                        continue
                    dim = "°" if (a or b)["n"] < 20 else ""
                    p3 = f"{a['net_pts']:+.1f}" if a else "—"
                    pn = f"{b['net_pts']:+.1f}" if b else "—"
                    cells.append(f"{dim}{p3} / {pn} "
                                 f"(n{(a or b)['n']})")
                L.append(f"| H{hn} | {name} | " + " | ".join(cells) + " |")
            L.append("")
        L += [f"### {inst} — BASELINES (controls — never candidates)", "",
              "> Pseudo-signals through the identical harvest machinery "
              "(ladder, sessions, spread, honest fills, one-position). "
              "PERMANENTLY excluded from hypothesis counts, labels, and "
              "promotion. B-TREND: with-trend fires every "
              f"{BASELINE_INTERVAL_BARS} bars (cadence FLAGGED "
              "implementer-proposed), established-trend gate mirrored "
              "from the trend family. B-RANDOM: uniform random "
              f"timing/direction, seed {BASELINE_SEED} (pinned). "
              "B-ALWAYS-LONG: periodic longs — the drift reference.", "",
              "| baseline | window | " + " | ".join(widths) + " |",
              "|---|---|" + "---|" * len(widths)]
        for bname in BASELINE_NAMES:
            brow = res["baselines"].get(bname, {})
            for win in ("backtest", "forward"):
                cells = [_fmt(brow.get(w, {}).get(win)) for w in widths]
                L.append(f"| {bname} | {win} | " + " | ".join(cells)
                         + " |")
        L.append("")
        if res["views"]:
            L += [f"### {inst} — OPEN QUESTIONS (conditioned views — NOT "
                  "registered signals)", "",
                  "> These three rows are the question-holding conditioned "
                  "views (register 58). They are session-selections of the "
                  "SAME simulated trades as the signal rows above "
                  "(identical fills; the one-position stream is the full "
                  "signal's). They grade their questions on the "
                  "conditioning matrix, not here — this is harvest "
                  "texture only.", "",
                  "| view | window | " + " | ".join(widths) + " |",
                  "|---|---|" + "---|" * len(widths)]
            for label, row in res["views"].items():
                for win in ("backtest", "forward"):
                    cells = [_fmt(row.get(w, {}).get(win)) for w in widths]
                    L.append(f"| {label} | {win} | " + " | ".join(cells)
                             + " |")
            L.append("")
    L += ["---", "", "Full width×session grid in "
          "reports/scoreboard/signal_points.json (same run)."]
    with open(PAGE, "w") as f:
        f.write("\n".join(L))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--instr", nargs="*",
                    default=["uk100fut", "ger40fut", "nas100fut", "us30fut"])
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                          capture_output=True, text=True).stdout.strip()
    results = []
    for instr in a.instr:
        print(f"# signal_points: {instr} ...", file=sys.stderr)
        results.append(run_instrument(instr))
    art = {"STAMP": ("OBSERVATIONAL stop-width ladder — measurement for "
                     "assessment and the values discussion, not promotion "
                     "evidence; never validation"),
           "engine_commit": head,
           "ladder": {"widths_atr15": list(LADDER_WIDTHS),
                      "nostop": "EOD-only exit (true no-SL endpoint)"},
           "baselines": {"names": list(BASELINE_NAMES),
                         "seed": BASELINE_SEED,
                         "interval_bars": BASELINE_INTERVAL_BARS,
                         "drift_skew_share_FLAGGED": DRIFT_SKEW_SHARE,
                         "fence": ("CONTROLS NEVER CANDIDATES — excluded "
                                   "from hypothesis counts, labels, and "
                                   "promotion machinery permanently")},
           "results": results}
    with open(os.path.join(OUT, "signal_points.json"), "w") as f:
        json.dump(art, f, indent=2, default=str)
    _emit(results, head)
    print(f"OBSERVATIONAL signal points -> {PAGE}")


if __name__ == "__main__":
    main()
